require:
  - rubocop-rails
AllCops:
  TargetRubyVersion:
    2.7
  Exclude:
    - 'db/schema.rb'
Layout/LineLength:
  Max: 100
Style/Documentation:
  Enabled: false
Rails/OutputSafety:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
